export const Thread = {
  ADD_BATCH: 'ADD_THREADS',
  SELECT: 'SELECT_THREAD',
  MULTISELECT: 'MULTISELECT_THREAD',
  REMOVE_LABEL: 'REMOVE_LABEL',
  ADD_LABEL: 'ADD_THREAD_LABEL',
  UNREAD_FILTER: 'UNREAD_FILTER'
};

export const User = {
  ADD_BATCH: 'ADD_USERS',
  ADD: 'ADD_USER'
};

export const Email = {
  ADD_BATCH: 'ADD_EMAILS'
};
