export const Thread = {
  ADD_BATCH: 'ADD_THREADS',
  ADD_LABEL: 'ADD_THREAD_LABEL',
  MULTISELECT: 'MULTISELECT_THREAD',
  REMOVE: 'REMOVE_THREAD',
  REMOVE_LABEL: 'REMOVE_LABEL',
  ADD_LABEL: 'ADD_THREAD_LABEL',
  SELECT: 'SELECT_THREAD',
  UNREAD_FILTER: 'UNREAD_FILTER'
};

export const User = {
  ADD: 'ADD_USER',
  ADD_BATCH: 'ADD_USERS'
};

export const Email = {
  ADD_BATCH: 'ADD_EMAILS'
};

export const Label = {
  ADD_BATCH: 'ADD_LABELS',
  ADD_LABEL: 'ADD_LABEL'
};

export const Feed = {
  ADD_BATCH: 'ADD_FEEDS'
}
