import {
  setAvatarUpdatedTimestamp,
  startLoadSync,
  startLoadThread,
  stopAll,
  stopLoadSync,
  stopLoadThread,
  updateLoadingSync,
  updateSwitchThreads
} from './activity';
import { addContacts, loadContacts } from './contacts';
import { addFiles, loadFiles, unsendEmailFiles } from './files';
import {
  addLabelIdThread,
  addLabelIdThreadSuccess,
  addLabelIdThreadDraft,
  addLabelIdThreads,
  addLabelIdThreadsSuccess,
  addMoveLabelIdThreads,
  addThreads,
  filterThreadsOrLoadMoreByUnread,
  loadEvents,
  loadThreads,
  moveThreads,
  removeAllThreads,
  removeLabelIdThread,
  removeLabelIdThreadSuccess,
  removeLabelIdThreadDraft,
  removeLabelIdThreads,
  removeLabelIdThreadsSuccess,
  updateEmailIdsThread,
  updateThreadsSuccess,
  updateUnreadThreads,
  removeThreads,
  removeThreadsDrafts,
  removeThreadsSuccess,
  sendOpenEvent,
  updateThread
} from './threads';
import {
  addEmails,
  loadEmails,
  markEmailUnread,
  muteEmail,
  muteNotifications,
  removeEmails,
  removeEmailsOnSuccess,
  unsendEmail,
  unsendEmailOnSuccess,
  updateEmailLabels,
  updateEmailOnSuccess
} from './emails';
import {
  addLabels,
  addLabel,
  removeLabel,
  removeLabelOnSuccess,
  removeLabels,
  updateBadgeLabels,
  updateLabel,
  updateLabels,
  updateLabelSuccess
} from './labels';
import {
  addFeedItems,
  loadFeedItems,
  removeFeedItem,
  removeFeedItemSuccess,
  updateFeedItem,
  updateFeedItems,
  updateFeedItemSuccess
} from './feeditems';
import { clearSuggestions, loadSuggestions } from './suggestions';
import { addDataApp, loadApp } from './app';

export {
  addContacts,
  addDataApp,
  addEmails,
  addFiles,
  addFeedItems,
  addLabel,
  addLabels,
  addLabelIdThread,
  addLabelIdThreadSuccess,
  addLabelIdThreadDraft,
  addLabelIdThreads,
  addLabelIdThreadsSuccess,
  addMoveLabelIdThreads,
  addThreads,
  clearSuggestions,
  filterThreadsOrLoadMoreByUnread,
  loadApp,
  loadContacts,
  loadEmails,
  loadEvents,
  loadFiles,
  loadFeedItems,
  loadSuggestions,
  loadThreads,
  markEmailUnread,
  moveThreads,
  muteEmail,
  muteNotifications,
  removeAllThreads,
  removeEmails,
  removeEmailsOnSuccess,
  removeLabel,
  removeLabelIdThread,
  removeLabelIdThreadSuccess,
  removeLabelIdThreadDraft,
  removeLabelIdThreads,
  removeLabelIdThreadsSuccess,
  removeLabelOnSuccess,
  removeLabels,
  removeFeedItem,
  removeFeedItemSuccess,
  removeThreads,
  removeThreadsDrafts,
  removeThreadsSuccess,
  sendOpenEvent,
  setAvatarUpdatedTimestamp,
  startLoadSync,
  startLoadThread,
  stopAll,
  stopLoadSync,
  stopLoadThread,
  unsendEmail,
  unsendEmailFiles,
  unsendEmailOnSuccess,
  updateBadgeLabels,
  updateFeedItem,
  updateFeedItems,
  updateFeedItemSuccess,
  updateEmailIdsThread,
  updateEmailLabels,
  updateEmailOnSuccess,
  updateLabel,
  updateLabels,
  updateLabelSuccess,
  updateLoadingSync,
  updateSwitchThreads,
  updateThread,
  updateThreadsSuccess,
  updateUnreadThreads
};
