export const App = {
  ADD_DATA: 'ADD_DATA_APP'
};

export const File = {
  ADD_BATCH: 'ADD_FILES',
  UNSEND_FILES: 'UNSEND_FILES'
};

export const Thread = {
  ADD_BATCH: 'ADD_THREADS',
  ADD_LABELID_THREAD: 'ADD_LABELID_THREAD',
  ADD_LABELID_THREADS: 'ADD_LABELID_THREADS',
  REMOVE_LABELID_THREAD: 'REMOVE_LABELID_THREAD',
  REMOVE_LABELID_THREADS: 'REMOVE_LABELID_THREADS',
  REMOVE_THREADS: 'REMOVE_THREADS',
  UPDATE_EMAILIDS_THREAD: 'UPDATE_EMAILIDS_THREAD',
  UPDATE_THREAD: 'UPDATE_THREAD',
  UPDATE_THREADS: 'UPDATE_THREADS',
  SEARCH_THREADS: 'SEARCH_THREADS',
  MOVE_THREADS: 'MOVE_THREADS'
};

export const Contact = {
  ADD_BATCH: 'ADD_CONTACTS'
};

export const Email = {
  ADD_BATCH: 'ADD_EMAILS',
  MUTE: 'MUTE_EMAIL',
  MARK_UNREAD: 'MARK_UNREAD_EMAIL',
  UNSEND: 'UNSEND_EMAIL',
  UPDATE: 'UPDATE_EMAIL',
  REMOVE_EMAILS: 'REMOVE_EMAILS'
};

export const Label = {
  ADD_BATCH: 'ADD_LABELS',
  UPDATE: 'UPDATE_LABEL',
  UPDATE_BADGE_LABELS: 'UPDATE_BADGE_LABELS',
  REMOVE: 'REMOVE_LABEL'
};

export const FeedItem = {
  ADD_BATCH: 'ADD_FEED_ITEMS',
  REMOVE_SUCCESS: 'REMOVE_FEED_ITEM',
  UPDATE_SUCCESS: 'UPDATE_FEED_ITEM',
  UPDATE_ALL: 'UPDATE_ALL_FEED_ITEMS'
};

export const Suggestions = {
  SET_THREADS: 'SET_THREADS',
  SET_ERROR_SUGGESTIONS: 'SET_ERROR_SUGGESTIONS'
};

export const Activity = {
  AVATAR_UPDATED_TIMESTAMP: 'AVATAR_UPDATED_TIMESTAMP',
  START_LOAD_SYNC: 'START_LOAD_SYNC',
  STOP_LOAD_SYNC: 'STOP_LOAD_SYNC',
  START_LOAD_THREAD: 'START_LOAD_THREAD',
  STOP_LOAD_THREAD: 'STOP_LOAD_THREAD',
  STOP_ALL: 'STOP_ALL',
  UNREAD_FILTER: 'FILTER_UNREAD_THREAD',
  UPDATE_LOADING_SYNC: 'UPDATE_LOADING_SYNC',
  UPDATE_SWITCH_THREADS: 'UPDATE_SWITCH_THREADS'
};
