export const Thread = {
  ADD_BATCH: 'ADD_THREADS',
  ADD_THREAD_LABEL: 'ADD_THREAD_LABEL',
  ADD_THREADS_LABEL: 'ADD_THREADS_LABEL',
  REMOVE: 'REMOVE_THREAD',
  REMOVE_LABEL: 'REMOVE_LABEL_THREAD',
  REMOVE_THREADS_LABEL: 'REMOVE_THREADS_LABEL',
  SELECT: 'SELECT_THREAD',
  UNREAD_FILTER: 'FILTER_UNREAD_THREAD',
  DESELECT_THREADS: 'DESELECT_THREADS',
  SELECT_THREADS: 'SELECT_THREADS',
  REMOVE_THREADS: 'REMOVE_THREADS',
  SEARCH_THREADS: 'SEARCH_THREADS',
  MOVE_THREADS: 'MOVE_THREADS',
  UPDATE_UNREAD_THREADS: 'UPDATE_UNREAD_THREADS',
  UPDATE_UNREAD_THREAD: 'UPDATE_UNREAD_THREAD'
};

export const Contact = {
  ADD_BATCH: 'ADD_CONTACTS'
};

export const Email = {
  ADD_BATCH: 'ADD_EMAILS',
  MUTE: 'MUTE_EMAIL',
  MARK_UNREAD: 'MARK_UNREAD_EMAIL'
};

export const Label = {
  ADD_BATCH: 'ADD_LABELS',
  UPDATE_SUCCESS: 'UPDATE_LABEL_SUCCESS'
};

export const Feed = {
  ADD_BATCH: 'ADD_FEEDS',
  SELECT: 'SELECT_FEED',
  REMOVE: 'REMOVE_FEED'
};

export const Suggestions = {
  SET_THREADS: 'SET_THREADS',
  SET_ERROR_SUGGESTIONS: 'SET_ERROR_SUGGESTIONS'
};

export const Activity = {
  START_LOAD_SYNC: 'START_LOAD_SYNC',
  STOP_LOAD_SYNC: 'STOP_LOAD_SYNC'
};
