export const Thread = {
  ADD_BATCH: 'ADD_THREADS',
  ADD_THREAD_LABEL: 'ADD_THREAD_LABEL',
  ADD_THREADS_LABEL: 'ADD_THREADS_LABEL',
  MULTISELECT: 'MULTISELECT_THREAD',
  REMOVE: 'REMOVE_THREAD',
  REMOVE_LABEL: 'REMOVE_LABEL_THREAD',
  REMOVE_THREADS_LABEL: 'REMOVE_THREADS_LABEL',
  SELECT: 'SELECT_THREAD',
  UNREAD_FILTER: 'FILTER_UNREAD_THREAD',
  DESELECT_THREADS: 'DESELECT_THREADS',
  SELECT_THREADS: 'SELECT_THREADS',
  REMOVE_THREADS: 'REMOVE_THREADS',
  SEARCH_THREADS: 'SEARCH_THREADS',
  MOVE_THREADS: 'MOVE_THREADS',
  READ_THREADS: 'READ_THREADS',
  MUTE_THREAD: 'MUTE_THREAD'
};

export const User = {
  ADD: 'ADD_USER',
  ADD_BATCH: 'ADD_USERS'
};

export const Email = {
  ADD_BATCH: 'ADD_EMAILS'
};

export const Label = {
  ADD_BATCH: 'ADD_LABELS',
  ADD_LABEL: 'ADD_LABEL'
};

export const Feed = {
  ADD_BATCH: 'ADD_FEEDS',
  SELECT: 'SELECT_FEED',
  REMOVE: 'REMOVE_FEED',
  TOGGLE_MUTE: 'TOGGLE_MUTE'
};
